version: "3"

volumes:
    logs:
        driver: local

services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html/
        networks:
            - default
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: geofencing
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./script:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root